name: Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Refresh (Optional but Recommended)
        run: terraform refresh
        working-directory: ./infrastructure

      - name: Show Current Resources (Safety Step)
        run: terraform state list
        working-directory: ./infrastructure

      - name: Confirm Deletion Step (Interactive for Safety)
        run: |
          echo "🚨 WARNING: You're about to destroy ALL infrastructure! 🚨"
          echo "If this is intentional, proceed. If not, cancel the workflow immediately."
          sleep 10

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./infrastructure